import { createFileRoute } from "@tanstack/react-router";
import { LegalLayout, LegalSection } from "@/components/masmer/LegalLayout";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Masmer AI" },
      {
        name: "description",
        content: "The terms governing your use of Masmer AI.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" subtitle="Last updated: May 10, 2026">
      <LegalSection title="1. Acceptance of Terms">
        <p>
          By accessing or using Masmer AI, you agree to be bound by these Terms
          of Service. If you do not agree, do not use the platform.
        </p>
        <p>
          These terms apply to all users including contractors, home improvement
          companies, and their team members.
        </p>
      </LegalSection>

      <LegalSection title="2. Description of Service">
        <p>
          Masmer AI is a business management platform designed for contractors
          and home improvement companies. The platform includes:
        </p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>AI-powered scope of work and estimate generation</li>
          <li>Materials list creation with Home Depot pricing</li>
          <li>Customer and project management (CRM)</li>
          <li>AI voice receptionist powered by Vapi</li>
          <li>Call logging and transcript management</li>
          <li>Document generation (contracts, punchlists)</li>
          <li>Day planning and route optimization tools</li>
        </ul>
      </LegalSection>

      <LegalSection title="3. Account Registration">
        <ul className="list-disc pl-6 space-y-1.5">
          <li>You must apply for access and be approved</li>
          <li>You are responsible for maintaining the security of your account credentials</li>
          <li>You must provide accurate and complete information during registration</li>
          <li>One account per business unless otherwise agreed</li>
          <li>You must be 18 or older to use the platform</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Acceptable Use">
        <p>You agree NOT to:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Share your account credentials with unauthorized users</li>
          <li>Use the platform for illegal purposes</li>
          <li>Attempt to reverse engineer or copy the platform</li>
          <li>Upload malicious code or content</li>
          <li>Misrepresent your identity or business</li>
          <li>Use the AI tools to generate fraudulent or misleading documents</li>
        </ul>
      </LegalSection>

      <LegalSection title="5. AI-Generated Content">
        <p>Important disclaimers about AI features:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Estimates and materials lists are generated by AI and are ESTIMATES ONLY</li>
          <li>All pricing is approximate and subject to change based on actual market conditions</li>
          <li>Home Depot pricing shown is approximate and may vary by location and availability</li>
          <li>Always verify materials costs before purchasing or providing quotes to customers</li>
          <li>Masmer AI is not responsible for pricing discrepancies between generated estimates and actual costs</li>
          <li>Contracts and scope of work documents generated by AI should be reviewed by you before sending to customers</li>
          <li>We strongly recommend having a lawyer review any contract templates for compliance with your local laws</li>
        </ul>
      </LegalSection>

      <LegalSection title="6. AI Receptionist & Call Recording">
        <p>By using the AI receptionist feature:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>You are responsible for complying with all applicable call recording laws in your jurisdiction</li>
          <li>You must inform callers that calls may be recorded</li>
          <li>You are responsible for how you use call transcripts and recordings</li>
          <li>Masmer AI is not liable for any legal issues arising from call recording</li>
        </ul>
      </LegalSection>

      <LegalSection title="7. Payment & Billing">
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Current pricing is displayed on our pricing page</li>
          <li>Demo access is provided free for 7 days</li>
          <li>Paid plans are billed monthly or annually</li>
          <li>Cancellation takes effect at end of current billing period</li>
          <li>No refunds for partial months</li>
          <li>We reserve the right to change pricing with 30 days notice</li>
        </ul>
      </LegalSection>

      <LegalSection title="8. Intellectual Property">
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Masmer AI platform and technology is owned by 607 The Home Improvement CCS Group</li>
          <li>You retain ownership of all data, projects, and documents you create</li>
          <li>You grant us a limited license to process your data to provide the service</li>
          <li>You may not copy, reproduce, or redistribute the platform</li>
        </ul>
      </LegalSection>

      <LegalSection title="9. Limitation of Liability">
        <p>
          Masmer AI and 607 The Home Improvement CCS Group shall not be liable
          for:
        </p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Inaccuracies in AI-generated estimates</li>
          <li>Business decisions made based on platform data</li>
          <li>Loss of data due to technical issues</li>
          <li>Any indirect, incidental, or consequential damages</li>
        </ul>
        <p>
          Our total liability is limited to the amount you paid us in the last 3
          months.
        </p>
      </LegalSection>

      <LegalSection title="10. Termination">
        <p>We reserve the right to:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Suspend or terminate accounts that violate these terms</li>
          <li>Discontinue the service with 30 days notice</li>
          <li>Modify features and functionality</li>
        </ul>
        <p>
          You may cancel your account at any time by contacting{" "}
          <a className="text-orange hover:underline" href="mailto:jacob@casacapsolutions.com">
            jacob@casacapsolutions.com
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection title="11. Changes to Terms">
        <p>
          We may update these terms at any time. We will notify you by email of
          significant changes. Continued use after changes constitutes acceptance
          of new terms.
        </p>
      </LegalSection>

      <LegalSection title="12. Governing Law">
        <p>
          These terms are governed by the laws of the State of New York. Any
          disputes shall be resolved in the courts of New York.
        </p>
      </LegalSection>

      <LegalSection title="13. Contact">
        <p>For terms questions or legal notices:</p>
        <p>
          Email:{" "}
          <a className="text-orange hover:underline" href="mailto:jacob@casacapsolutions.com">
            jacob@casacapsolutions.com
          </a>
          <br />
          Company: 607 The Home Improvement CCS Group
          <br />
          Operating as: Masmer AI
        </p>
      </LegalSection>
    </LegalLayout>
  );
}