/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/estimate'
    | '/login'
    | '/projects'
    | '/customers/$id'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/estimate'
    | '/login'
    | '/projects'
    | '/customers/$id'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/estimate'
    | '/login'
    | '/projects'
    | '/customers/$id'
    | '/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EstimateRoute: typeof EstimateRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EstimateRoute: EstimateRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
